### PR TITLE
Merge stall notice into `master`

### PR DESCRIPTION
**Pull request by amonks**
I started making a _yeah_ game a few days ago and only just noticed the stall notice.
### A friendly rebuttal:

I agree with you that, "A game's level of quality actually has nothing to do with its level of support for multiple disparate platforms" but I'd add that game quality doesn't always correlate to computation speed, either. Some games, like _Phoenix Wright_, _Final Fantasy Tactics_, or (lol) _NetHack_, might benefit from Ruby's expressiveness while not suffering from it's slowness.

I'm not sure if I'll stick with _yeah_ for my (slow, turn-based) game, and I obviously can't claim that it's the right tool for everyone, but I think a game framework in Ruby is a pretty delightful idea :smile_cat:

### CODE REVIEW

**Comment by skofo** [comment]
You make good points. I, too, can imagine the games you listed being successfully implemented using Ruby.

The big issue with Yeah boils down to this: the current architecture makes it unnecessarily hard to create games that perform well. Yeah's central feature is a vector drawing API, which is neat, but prevents the possibility of behind-the-scenes game drawing optimizations, and is not particularly useful for creating video games to begin with.

A Ruby game framework is indeed a delightful idea, and it might be possible to execute well. But Yeah is not executed well as a game framework, and I am personally looking for more flexiblity and performance in a game development tool than I think would be possible with a Ruby game framework, even a well-executed one. It's just a personal taste - I want to make trigonometry-heavy action games.

The most useful part of Yeah is the web-based Processing-like API. My future plan is to convert my efforts to an opal-processing; that is, Opal bindings for Processing.js. This would maximize the usefulness of this type of project, because it would be inteoperable with ruby-processing and the larger Processing ecosystem.

Thanks for bringing this up to allow me to clarify my thoughts. If there is something else you want me to touch on, let me know!

**Comment by amonks** [comment]
Thanks for your well considered response. I totally see where you're coming from. Maybe in a few decades Moore's law // better implementations might make Ruby a plausible choice for realtime systems but it sure isn't there yet. Cool project anyway! Good luck with your next one!

Piggybacking on the Processing ecosystem with Opal is a great idea. I'll look forward to seeing where that goes!


I still think you should merge your stall notice onto master (or set webgl as the default branch) so it's visible on [yeahrb/yeah](/yeahrb/yeah)

**Comment by skofo** [comment]
I think the performance issue is caused by Yeah more than it is by Ruby. I think it is feasible to create good-performing games in Ruby like Pheonix Wright, Final Fantasy Tactics and Nethack, just with a differently designed framework.

**Comment by amonks** [comment]
I agree completely.

**Pull request closed without merging**
